apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  ports:
    - port: 3306
      targetPort: 3306  # Replace with the actual port number if not 3306
      protocol: TCP
  selector:
    app: vprodb
  type: ClusterIP